site_name: ComitÃª CientÃ­fico do MONAN 
site_url: https://monanadmin.github.io/monan_cc_docs  
site_author: Carlos Frederico Bastarz
site_description: Site com as Atas das ReuniÃµes do ComitÃª CientÃ­fico do MONAN

repo_name: monanadmin/monan_cc_docs
repo_url: https://github.com/monanadmin/monan_cc_docs
edit_uri: edit/master/docs/

docs_dir: docs/
exclude_docs: overrides/

copyright: Copyright Â© 2021-2025 - MONAN  

theme: 
  name: material
    #font: false  
  #language: pt-BR
  custom_dir: docs/overrides
  #features:
    #- navigation.expand
    #- navigation.indexes
    #- navigation.sections
    #- navigation.tabs
    #- toc.follow
    #- toc.integrate
    #    - i18n
  icon:
    #logo: material/book-open-page-variant
    logo: material/school
    repo: fontawesome/brands/github

extra:
    social:
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/@monan-model
      - icon: fontawesome/brands/github
        link: https://github.com/monanadmin
      - icon: fontawesome/solid/paper-plane
        link: mailto:mcstu.inpe@gmail.com

extra_css:
- stylesheets/extra.css

extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js
- javascripts/voronoi.js  

markdown_extensions:
  - md_in_html  
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - ğŸ“„ Atas 2021:
    - 'â—¾05 de Maio de 2021': pages/ata_cc_05_maio_2021.md
    - 'â—¾04 de Junho de 2021': pages/ata_cc_04_junho_2021.md
    - 'â—¾30 de Agosto de 2021': pages/ata_cc_30_agosto_2021.md
    - 'â—¾04 de Novembro de 2021': pages/ata_cc_04_novembro_2021.md
    - 'â—¾06 de Dezembro de 2021': pages/ata_cc_06_dezembro_2021.md
  - ğŸ“„ Atas 2022:
    - 'â—¾28 de MarÃ§o de 2022': pages/ata_cc_28_marco_2022.md
    - 'â—¾13 de Outubro de 2022': pages/ata_cc_13_outubro_2022.md
  - ğŸ“„ Atas 2023:
    - 'â—¾03 de Agosto de 2023': pages/ata_cc_03_agosto_2023.md
  - ğŸ“„ Atas 2024:
    - 'â—¾05 de MarÃ§o de 2024': pages/ata_cc_05_marco_2024.md
    - 'â—¾04 de Dezembro de 2024': pages/ata_cc_04_dezembro_2024.md
  - ğŸ“„ Atas 2025:
    - 'â—¾10 de Junho de 2025': pages/ata_cc_10_junho_2025.md
  - ğŸ“¯ AnÃºncios:
    - ğŸ¯ Oportunidades: pages/oportunidades.md
    - ğŸ’¬ SeminÃ¡rios:
      - 'â—¾SeminÃ¡rios Institucionais': pages/seminarios.md
      - 'â—¾SeminÃ¡rios ATOS-BULL': pages/seminarios_atos_bull.md
      - 'â—¾SeminÃ¡rios NVIDIA': pages/seminarios_nvidia.md
  - ğŸ—ƒ Arquivos:
    - 'â—¾Carta de ApresentaÃ§Ã£o do MONAN': pages/carta_apres_monan.md
    - 'â—¾Portaria INPE': pages/portaria_inpe.md  
    - 'â—¾RelatÃ³rios': pages/relatorios.md
    - 'â—¾Outros Arquivos': pages/outros_arquivos.md
  - ğŸ‘¨ Membros: pages/membros.md
  - ğŸ› SubcomitÃªs: pages/subcomites.md
  - âš™ Recursos:
    - 'â—¾Logo MONAN': pages/logo_monan.md
  - ğŸ–¥ Treinamentos:
    - 'â—¾Agosto de 2024': pages/treinamento_agosto_2024.md
  - ğŸ“š Tutoriais: pages/tutoriais.md
  - ğŸ“° Clipping: pages/clipping.md

plugins:
  - mkdocs-video
  - search
  - glightbox
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: pt-BR
          default: true
          name: "ğŸ‡§ğŸ‡· PortuguÃªs"
          build: true
          site_name: "ComitÃª CientÃ­fico do MONAN"
        - locale: es
          name: "ğŸ‡ªğŸ‡¸ EspaÃ±ol"
          build: true
          site_name: "ComitÃ© CientÃ­fico del MONAN"
          nav_translations:
              ğŸ“„ Atas 2021: "ğŸ“„ Actas 2021"
              â—¾05 de Maio de 2021: "â—¾05 de Mayo de 2021"
              â—¾04 de Junho de 2021: "â—¾04 de Junio de 2021"
              â—¾30 de Agosto de 2021: "â—¾30 de Agosto de 2021"
              â—¾04 de Novembro de 2021: "â—¾04 de Noviembre de 2021"
              â—¾06 de Dezembro de 2021: "â—¾06 de Diciembre de 2021"
              ğŸ“„ Atas 2022: "ğŸ“„ Actas 2022"
              â—¾28 de MarÃ§o de 2022: "â—¾28 de Marzo de 2022"
              â—¾13 de Outubro de 2022: "â—¾13 de Octubre de 2022"
              ğŸ“„ Atas 2023: "ğŸ“„ Actas 2023"
              â—¾03 de Agosto de 2023: "â—¾03 de Agosto de 2023"
              ğŸ“„ Atas 2024: "ğŸ“„ Actas 2024"
              â—¾05 de MarÃ§o de 2024: "â—¾05 de Marzo de 2024"
              â—¾04 de Dezembro de 2024: "â—¾04 de Diciembre de 2024"
              ğŸ“„ Atas 2025: "ğŸ“„ Actas 2025"
              â—¾10 de Junho de 2025: "â—¾10 de Junio de 2025"
              ğŸ“¯ AnÃºncios: "ğŸ“¯ Anuncios"  
              ğŸ–¥ Treinamentos: "ğŸ–¥ Entrenamientos"
              â—¾Agosto de 2024: "â—¾Agosto de 2024"
              ğŸ¯ Oportunidades: "ğŸ¯ Oportunidades"
              ğŸ’¬ SeminÃ¡rios: "ğŸ’¬ Seminarios"  
              â—¾SeminÃ¡rios Institucionais: "â—¾Seminarios Institucionales"
              â—¾SeminÃ¡rios ATOS-BULL: "â—¾Seminarios ATOS-BULL"
              â—¾SeminÃ¡rios NVIDIA: "â—¾Seminarios NVIDIA"
              ğŸ—ƒ Arquivos: "ğŸ—ƒ Archivos"
              â—¾Carta de ApresentaÃ§Ã£o do MONAN: "â—¾Carta de presentaciÃ³n del MONAN"
              â—¾Portaria INPE: "â—¾ResoluciÃ³n INPE"
              â—¾RelatÃ³rios: "â—¾Informes"
              â—¾Outros Arquivos: "â—¾Otros Archivos"
              ğŸ‘¨ Membros: "ğŸ‘¨ Miembros"  
              ğŸ› SubcomitÃªs: "ğŸ› SubcomitÃ©s"
              âš™ Recursos: "âš™ Recursos"
              â—¾Logo MONAN: "â—¾MONAN Logo"
              ğŸ“š Tutoriais: "ğŸ“š Tutoriales"  
              ğŸ“° Clipping: "ğŸ“° Resumen de Prensa"
        - locale: en
          name: "ğŸ‡ºğŸ‡¸ English"
          build: true
          site_name: "MONAN Scientific Comittee"
          nav_translations:
              ğŸ“„ Atas 2021: "ğŸ“„ Minutes 2021"
              â—¾05 de Maio de 2021: "â—¾May 5, 2021"
              â—¾04 de Junho de 2021: "â—¾June 4, 2021"
              â—¾30 de Agosto de 2021: "â—¾August 30, 2021"
              â—¾04 de Novembro de 2021: "â—¾November 4, 2021"
              â—¾06 de Dezembro de 2021: "â—¾December 6, 2021"
              ğŸ“„ Atas 2022: "ğŸ“„ Minutes 2022"
              â—¾28 de MarÃ§o de 2022: "â—¾March 28, 2022"
              â—¾13 de Outubro de 2022: "â—¾October 13, 2022"
              ğŸ“„ Atas 2023: "ğŸ“„ Minutes 2023"
              â—¾03 de Agosto de 2023: "â—¾August 3, 2023"
              ğŸ“„ Atas 2024: "ğŸ“„ Minutes 2024"
              â—¾05 de MarÃ§o de 2024: "â—¾March 5, 2024"
              â—¾04 de Dezembro de 2024: "â—¾December 4, 2024"
              ğŸ“„ Atas 2025: "ğŸ“„ Minutes 2025"
              â—¾10 de Junho de 2025: "â—¾June 10, 2025"
              ğŸ“¯ AnÃºncios: "ğŸ“¯ Ads"  
              ğŸ–¥ Treinamentos: "ğŸ–¥ Trainings"
              â—¾Agosto de 2024: "â—¾August, 2024"
              ğŸ¯ Oportunidades: "ğŸ¯ Opportunities"
              ğŸ’¬ SeminÃ¡rios: "ğŸ’¬ Seminnars"
              â—¾SeminÃ¡rios Institucionais: "â—¾Institutional Semminars"
              â—¾SeminÃ¡rios ATOS-BULL: "â—¾ATOS-BULL Semminars"
              â—¾SeminÃ¡rios NVIDIA: "â—¾NVIDIA Semminars"
              ğŸ—ƒ Arquivos: "ğŸ—ƒ Archives"  
              â—¾Carta de ApresentaÃ§Ã£o do MONAN: "â—¾MONAN Cover Letter"
              â—¾Portaria INPE: "â—¾INPE Administrative Order"
              â—¾RelatÃ³rios: "â—¾Reports"
              â—¾Outros Arquivos: "â—¾Other Files"
              ğŸ‘¨ Membros: "ğŸ‘¨ Members"  
              ğŸ› SubcomitÃªs: "ğŸ› Subcommittees"
              âš™ Recursos: "âš™ Resources"
              â—¾Logo MONAN: "â—¾MONAN Logo"
              ğŸ“š Tutoriais: "ğŸ“š Tutorials"
              ğŸ“° Clipping: "ğŸ“° Clipping"
    
